### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by TLengert** [dannoe/7DTD_ManualFixCrashedWorlds#1]
Excuse my ignorance, new to 7DTD servers, but how will this work in MP? I did not see any player role number features to, for example, only allow admin and mods to use the command.

**Comment by dannoe** [comment]
I am sorry that I didn't explicitly specify that this plugin is intended for singleplayer only. 

All my commands will output an error if they are used on a dedicated multiplayer server. It can be used for a multiplayer game that is started from the client, but only the host will receive the results from the commands.

Update: I will add a readme in the next days to explicit state this.

**Comment by dannoe** [comment]
I added the ability to use this plugin on a multiplayer (dedicated) server. You can test it if you want.
The user who wants to execute any of the commands needs a permission level of 0 (admin).
